package test.service;

import com.yandex.fz4.model.*;
import com.yandex.fz4.service.TaskManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public abstract class TaskManagerTest<T extends TaskManager> {
    protected T taskManager;

    protected abstract T createTaskManager();

    @BeforeEach
    void setUp() {
        taskManager = createTaskManager();
    }

    // Тесты для проверки равенства задач по ID
    @Test
    void testTasksAreEqualIfIdEqual() {
        Task t1 = new Task("T", "D");
        t1.setId(1);
        t1.setStatus(TaskStatus.NEW);

        Task t2 = new Task("T2", "D2");
        t2.setId(1);
        t2.setStatus(TaskStatus.DONE);

        assertEquals(t1, t2);
    }

    @Test
    void testSubtaskAndEpicAreEqualIfIdEqual() {
        Epic e1 = new Epic("E", "D");
        e1.setId(5);
        e1.setStatus(TaskStatus.NEW);

        Epic e2 = new Epic("E2", "D2");
        e2.setId(5);
        e2.setStatus(TaskStatus.DONE);

        assertEquals(e1, e2);

        Subtask s1 = new Subtask("S", "D", 2);
        s1.setId(10);
        s1.setStatus(TaskStatus.NEW);

        Subtask s2 = new Subtask("S2", "D2", 2);
        s2.setId(10);
        s2.setStatus(TaskStatus.DONE);

        assertEquals(s1, s2);
    }

    // Тесты для валидации данных
    @Test
    void testEpicCannotContainItselfAsSubtask() {
        Epic epic = new Epic("Epic", "Description");
        epic.setId(1);
        taskManager.addEpic(epic);

        Subtask validSubtask = new Subtask("Subtask", "Desc", epic.getId());
        taskManager.addSubtask(validSubtask);

        // Попытка добавить подзадачу с ID эпика (не должна добавиться)
        epic.addSubtaskId(epic.getId());

        assertFalse(epic.getSubtasksIds().contains(epic.getId()), "Epic не должен содержать сам себя");
    }

    @Test
    void testSubtaskCannotBeItsOwnEpic() {
        Subtask subtask = new Subtask("S", "D", 42);
        subtask.setId(42);

        assertNotEquals(subtask.getId(), subtask.getEpicId(), "Subtask не может ссылаться на себя как на эпик");
    }

    // Основные тесты функциональности
    @Test
    void testTaskManagerAddsAndFindsTasksById() {
        Task task = taskManager.addTask(new Task("T", "D"));
        Epic epic = taskManager.addEpic(new Epic("E", "D"));
        Subtask sub = taskManager.addSubtask(new Subtask("S", "D", epic.getId()));

        assertEquals(task, taskManager.getTaskById(task.getId()));
        assertEquals(epic, taskManager.getEpicById(epic.getId()));
        assertEquals(sub, taskManager.getSubtaskById(sub.getId()));
    }

    @Test
    void testManualAndAutoGeneratedIdsDoNotConflict() {
        Epic epic = taskManager.addEpic(new Epic("E", "D"));

        // Ручная установка ID (имитация)
        Subtask manual = new Subtask("Manual", "D", epic.getId());
        manual.setId(99);

        // Автогенерация ID
        Subtask auto = taskManager.addSubtask(new Subtask("Auto", "D", epic.getId()));

        assertNotEquals(99, auto.getId(), "Сгенерированный id не должен совпадать с ручным");
    }

    @Test
    void testTaskIsNotChangedByManagerOnAdd() {
        Task original = new Task("T", "D");
        String originalName = original.getName();
        String originalDesc = original.getDescription();
        TaskStatus originalStatus = original.getStatus();

        Task added = taskManager.addTask(original);

        assertEquals(originalName, added.getName());
        assertEquals(originalDesc, added.getDescription());
        assertEquals(originalStatus, added.getStatus());
        assertNotEquals(0, added.getId(), "У задачи должен быть присвоен уникальный id");
    }

    @Test
    void testManagerAddsTasksToHistoryWhenGetMethodsCalled() {
        Task t = taskManager.addTask(new Task("HistoryTask", "Tracked"));
        Epic e = taskManager.addEpic(new Epic("HistoryEpic", "Tracked"));
        Subtask s = taskManager.addSubtask(new Subtask("HistorySub", "Tracked", e.getId()));

        taskManager.getTaskById(t.getId());
        taskManager.getEpicById(e.getId());
        taskManager.getSubtaskById(s.getId());

        List<Task> history = taskManager.getHistory();
        assertEquals(3, history.size());
    }

    // Тесты для основных операций
    @Test
    void testAddAndGetTask() {
        Task task = new Task("Test Task", "Description");
        taskManager.addTask(task);

        Task retrieved = taskManager.getTaskById(task.getId());
        assertNotNull(retrieved);
        assertEquals("Test Task", retrieved.getName());
        assertEquals("Description", retrieved.getDescription());
        assertEquals(TaskStatus.NEW, retrieved.getStatus());
    }

    @Test
    void testGetAllTasks() {
        Task task1 = new Task("Task 1", "Desc 1");
        Task task2 = new Task("Task 2", "Desc 2");

        taskManager.addTask(task1);
        taskManager.addTask(task2);

        List<Task> tasks = taskManager.getTasks();
        assertEquals(2, tasks.size());
    }

    @Test
    void testUpdateTask() {
        Task task = new Task("Original", "Desc");
        taskManager.addTask(task);

        task.setName("Updated");
        task.setDescription("Updated Desc");
        task.setStatus(TaskStatus.IN_PROGRESS);

        taskManager.updateTask(task);

        Task updated = taskManager.getTaskById(task.getId());
        assertEquals("Updated", updated.getName());
        assertEquals("Updated Desc", updated.getDescription());
        assertEquals(TaskStatus.IN_PROGRESS, updated.getStatus());
    }

    @Test
    void testRemoveTask() {
        Task task = new Task("To Remove", "Desc");
        taskManager.addTask(task);

        taskManager.removeTaskById(task.getId());

        assertNull(taskManager.getTaskById(task.getId()));
        assertTrue(taskManager.getTasks().isEmpty());
    }

    @Test
    void testClearTasks() {
        Task task1 = new Task("Task 1", "Desc 1");
        Task task2 = new Task("Task 2", "Desc 2");

        taskManager.addTask(task1);
        taskManager.addTask(task2);

        taskManager.clearTasks();

        assertTrue(taskManager.getTasks().isEmpty());
    }

    // Тесты для Epic
    @Test
    void testAddAndGetEpic() {
        Epic epic = new Epic("Test Epic", "Description");
        taskManager.addEpic(epic);

        Epic retrieved = taskManager.getEpicById(epic.getId());
        assertNotNull(retrieved);
        assertEquals("Test Epic", retrieved.getName());
        assertEquals("Description", retrieved.getDescription());
        assertEquals(TaskStatus.NEW, retrieved.getStatus());
    }

    @Test
    void testUpdateEpic() {
        Epic epic = new Epic("Original", "Desc");
        taskManager.addEpic(epic);

        epic.setName("Updated");
        epic.setDescription("Updated Desc");

        taskManager.updateEpic(epic);

        Epic updated = taskManager.getEpicById(epic.getId());
        assertEquals("Updated", updated.getName());
        assertEquals("Updated Desc", updated.getDescription());
    }

    // Тесты для Subtask
    @Test
    void testAddAndGetSubtask() {
        Epic epic = new Epic("Parent Epic", "Desc");
        taskManager.addEpic(epic);

        Subtask subtask = new Subtask("Test Subtask", "Description", epic.getId());
        taskManager.addSubtask(subtask);

        Subtask retrieved = taskManager.getSubtaskById(subtask.getId());
        assertNotNull(retrieved);
        assertEquals("Test Subtask", retrieved.getName());
        assertEquals("Description", retrieved.getDescription());
        assertEquals(TaskStatus.NEW, retrieved.getStatus());
        assertEquals(epic.getId(), retrieved.getEpicId());
    }

    @Test
    void testUpdateSubtask() {
        Epic epic = new Epic("Parent Epic", "Desc");
        taskManager.addEpic(epic);

        Subtask subtask = new Subtask("Original", "Desc", epic.getId());
        taskManager.addSubtask(subtask);

        subtask.setName("Updated");
        subtask.setDescription("Updated Desc");
        subtask.setStatus(TaskStatus.DONE);

        taskManager.updateSubtask(subtask);

        Subtask updated = taskManager.getSubtaskById(subtask.getId());
        assertEquals("Updated", updated.getName());
        assertEquals("Updated Desc", updated.getDescription());
        assertEquals(TaskStatus.DONE, updated.getStatus());
    }

    // Тесты для статусов Epic
    @Test
    void testEpicStatusAllNew() {
        Epic epic = new Epic("Epic", "Description");
        taskManager.addEpic(epic);

        Subtask subtask1 = new Subtask("Sub1", "Desc", epic.getId());
        Subtask subtask2 = new Subtask("Sub2", "Desc", epic.getId());

        taskManager.addSubtask(subtask1);
        taskManager.addSubtask(subtask2);

        assertEquals(TaskStatus.NEW, epic.getStatus());
    }

    @Test
    void testEpicStatusAllDone() {
        Epic epic = new Epic("Epic", "Description");
        taskManager.addEpic(epic);

        Subtask subtask1 = new Subtask("Sub1", "Desc", epic.getId());
        Subtask subtask2 = new Subtask("Sub2", "Desc", epic.getId());

        subtask1.setStatus(TaskStatus.DONE);
        subtask2.setStatus(TaskStatus.DONE);

        taskManager.addSubtask(subtask1);
        taskManager.addSubtask(subtask2);
        taskManager.updateEpicStatus(epic.getId());

        assertEquals(TaskStatus.DONE, epic.getStatus());
    }

    @Test
    void testEpicStatusMixedNewDone() {
        Epic epic = new Epic("Epic", "Description");
        taskManager.addEpic(epic);

        Subtask subtask1 = new Subtask("Sub1", "Desc", epic.getId());
        Subtask subtask2 = new Subtask("Sub2", "Desc", epic.getId());

        subtask1.setStatus(TaskStatus.NEW);
        subtask2.setStatus(TaskStatus.DONE);

        taskManager.addSubtask(subtask1);
        taskManager.addSubtask(subtask2);
        taskManager.updateEpicStatus(epic.getId());

        assertEquals(TaskStatus.IN_PROGRESS, epic.getStatus());
    }

    @Test
    void testEpicStatusInProgress() {
        Epic epic = new Epic("Epic", "Description");
        taskManager.addEpic(epic);

        Subtask subtask1 = new Subtask("Sub1", "Desc", epic.getId());
        subtask1.setStatus(TaskStatus.IN_PROGRESS);

        taskManager.addSubtask(subtask1);
        taskManager.updateEpicStatus(epic.getId());

        assertEquals(TaskStatus.IN_PROGRESS, epic.getStatus());
    }

    @Test
    void testEpicStatusNoSubtasks() {
        Epic epic = new Epic("Epic", "Description");
        taskManager.addEpic(epic);

        assertEquals(TaskStatus.NEW, epic.getStatus());
    }

    // Тесты для получения подзадач по Epic
    @Test
    void testGetSubtasksByEpicId() {
        Epic epic = new Epic("Epic", "Description");
        taskManager.addEpic(epic);

        Subtask subtask1 = new Subtask("Sub1", "Desc", epic.getId());
        Subtask subtask2 = new Subtask("Sub2", "Desc", epic.getId());

        taskManager.addSubtask(subtask1);
        taskManager.addSubtask(subtask2);

        List<Subtask> epicSubtasks = taskManager.getSubtasksByEpicId(epic.getId());
        assertEquals(2, epicSubtasks.size());
    }

    // Тесты для истории
    @Test
    void testGetHistoryReturnsList() {
        Task task = new Task("Test", "Desc");
        taskManager.addTask(task);
        taskManager.getTaskById(task.getId());

        List<Task> history = taskManager.getHistory();
        assertNotNull(history);
        assertEquals(1, history.size());
        assertEquals(task.getId(), history.get(0).getId());
    }

    @Test
    void testHistoryNoDuplicates() {
        Task task = new Task("Test", "Desc");
        taskManager.addTask(task);

        taskManager.getTaskById(task.getId());
        taskManager.getTaskById(task.getId());
        taskManager.getTaskById(task.getId());

        List<Task> history = taskManager.getHistory();
        assertEquals(1, history.size());
    }

    // Тесты для обработки ошибок
    @Test
    void testGetNonExistentTask() {
        assertNull(taskManager.getTaskById(999));
    }

    @Test
    void testGetNonExistentEpic() {
        assertNull(taskManager.getEpicById(999));
    }

    @Test
    void testGetNonExistentSubtask() {
        assertNull(taskManager.getSubtaskById(999));
    }

    @Test
    void testRemoveNonExistentTask() {
        assertDoesNotThrow(() -> taskManager.removeTaskById(999));
    }

    // Тесты для новых функций (время и приоритеты)
    @Test
    void testTaskWithTimeProperties() {
        Task task = new Task("Test", "Desc");
        LocalDateTime startTime = LocalDateTime.of(2024, 1, 1, 10, 0);
        task.setStartTime(startTime);
        task.setDuration(60);

        taskManager.addTask(task);
        Task retrieved = taskManager.getTaskById(task.getId());

        assertEquals(startTime, retrieved.getStartTime());
        assertEquals(60, retrieved.getDuration());
        assertEquals(startTime.plusMinutes(60), retrieved.getEndTime());
    }

    @Test
    void testGetPrioritizedTasks() {
        Task earlyTask = new Task("Early", "Desc");
        earlyTask.setStartTime(LocalDateTime.of(2024, 1, 1, 10, 0));

        Task lateTask = new Task("Late", "Desc");
        lateTask.setStartTime(LocalDateTime.of(2024, 1, 1, 12, 0));

        taskManager.addTask(earlyTask);
        taskManager.addTask(lateTask);

        var prioritized = taskManager.getPrioritizedTasks();
        assertEquals(2, prioritized.size());
    }

    @Test
    void testTimeOverlapDetection() {
        Task task1 = new Task("Task1", "Desc");
        task1.setStartTime(LocalDateTime.of(2024, 1, 1, 10, 0));
        task1.setDuration(60);

        Task task2 = new Task("Task2", "Desc");
        task2.setStartTime(LocalDateTime.of(2024, 1, 1, 10, 30));
        task2.setDuration(60);

        taskManager.addTask(task1);

        assertThrows(IllegalArgumentException.class, () -> {
            taskManager.addTask(task2);
        }, "Должно быть исключение при пересечении времени");
    }
}